### ISSUE TITLE
Question. =D

### ISSUE THREAD

**Issue by mrc4tt** [Brambler/CSGO-Automation#1]
Hi. @Brambler 

I would like to hear, about it's possible to "track" after GOTV via screen IDs?

As example:
1) I'm running CSGO Server(s) on shared files (eg: `/home/gs/csgo/csgo/`)
2) Running CSGO Server(s) on each "screen ID" via screen (function)
3) Creating screenID folder via ``/var/www/html/screenIDhere`` and copy demofile to the screenID folder.

About it's possible to make, so it tracking after: ``Completed GOTV demo "%s.dem", recording time x.x`` and ln -s or move the .dem file to screen ID's folder? Eg: ``/var/www/html/demos/screenID/%s.dem``

As example could be: screenID: WiRjeXXj **=>** `Completed GOTV demo "1234.dem` **=>** copying `1234.dem` to this folder: `/var/www/html/demos/WiRjeXXj/` **=>**  `/var/www/html/demos/WiRjeXXj/1234.dem`

Thank you! ;) and sorry for disturb. ^^
Sorry for the bad english. ;)

**Comment by mrc4tt** [comment]
I don't think, @Brambler is active with the CSGO stuff. :(

**Comment by Brambler** [comment]
I think if in your config for the actual get5 plugin you specify a name for your demo file. You would need to figure out a way to auto append the screen ID to that config though, that way you can identify where the demo came from. Sorry for no reply didn't see this one come in.

And yeah I haven't touched the CSGO stuff for a while :P
